import htmlmin from 'html-minifier-terser';

const isProduction = process.env.NODE_ENV === 'production';

export default eleventyConfig => {
  eleventyConfig.addTransform('minifyHTML', (content, path) => {
    if (path && path.endsWith('.html') && isProduction) {
      return htmlmin.minify(content, {
        useShortDoctype: true,
        collapseBooleanAttributes: true,
        collapseWhitespace: true,
        decodeEntities: true,
        includeAutoGeneratedTags: false,
        removeComments: true
      });
    }

    return content;
  });
};